// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mikan/shared/models/announcement.dart';
import 'package:mikan/shared/models/bangumi.dart';
import 'package:mikan/shared/models/bangumi_row.dart';
import 'package:mikan/shared/models/carousel.dart';
import 'package:mikan/shared/models/index.dart';
import 'package:mikan/shared/models/record_item.dart';
import 'package:mikan/shared/models/season.dart';
import 'package:mikan/shared/models/subgroup.dart';
import 'package:mikan/shared/models/user.dart';
import 'package:mikan/shared/models/year_season.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AnnouncementNodeAdapter());
    registerAdapter(BangumiAdapter());
    registerAdapter(BangumiRowAdapter());
    registerAdapter(CarouselAdapter());
    registerAdapter(IndexAdapter());
    registerAdapter(RecordItemAdapter());
    registerAdapter(SeasonAdapter());
    registerAdapter(SubgroupAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(YearSeasonAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AnnouncementNodeAdapter());
    registerAdapter(BangumiAdapter());
    registerAdapter(BangumiRowAdapter());
    registerAdapter(CarouselAdapter());
    registerAdapter(IndexAdapter());
    registerAdapter(RecordItemAdapter());
    registerAdapter(SeasonAdapter());
    registerAdapter(SubgroupAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(YearSeasonAdapter());
  }
}
