// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:mikan/model/announcement.dart';
import 'package:mikan/model/bangumi.dart';
import 'package:mikan/model/bangumi_row.dart';
import 'package:mikan/model/carousel.dart';
import 'package:mikan/model/index.dart';
import 'package:mikan/model/record_item.dart';
import 'package:mikan/model/season.dart';
import 'package:mikan/model/subgroup.dart';
import 'package:mikan/model/user.dart';
import 'package:mikan/model/year_season.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AnnouncementNodeAdapter());
    registerAdapter(BangumiAdapter());
    registerAdapter(BangumiRowAdapter());
    registerAdapter(CarouselAdapter());
    registerAdapter(IndexAdapter());
    registerAdapter(RecordItemAdapter());
    registerAdapter(SeasonAdapter());
    registerAdapter(SubgroupAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(YearSeasonAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AnnouncementAdapter());
    registerAdapter(AnnouncementNodeAdapter());
    registerAdapter(BangumiAdapter());
    registerAdapter(BangumiRowAdapter());
    registerAdapter(CarouselAdapter());
    registerAdapter(IndexAdapter());
    registerAdapter(RecordItemAdapter());
    registerAdapter(SeasonAdapter());
    registerAdapter(SubgroupAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(YearSeasonAdapter());
  }
}
