// dart format off
// coverage:ignore-file
// ignore_for_file: duplicate_import,implementation_imports,library_private_types_in_public_api,multiple_combinators,prefer_const_literals_to_create_immutables,unintended_html_in_doc_comment,unnecessary_import,unnecessary_library_directive,unnecessary_library_name,unused_import,unused_local_variable,unused_shown_name
//
// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************
// fast mode: true
// **************************************************************************
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

import '../../../../shared/models/record_item.dart';
import '../../../../shared/models/season.dart';
import '../../../../shared/models/season_gallery.dart';
import '../../../../shared/models/year_season.dart';
import '../../../shared/models/season.dart';
import '../../../shared/models/subgroup.dart';
import '../../../shared/models/year_season.dart';
import 'features/auth/ui/forgot_password.dart';
import 'features/auth/ui/login.dart';
import 'features/auth/ui/register.dart';
import 'features/bangumi/ui/announcement.dart';
import 'features/bangumi/ui/subgroup.dart';
import 'features/home/ui/home.dart';
import 'features/season/ui/season_bangumi.dart';
import 'features/season/ui/single_season.dart';
import 'features/settings/ui/splash.dart';
import 'features/subscription/ui/recent_subscribed.dart';
import 'features/subscription/ui/subscribed_season.dart';
import 'shared/ui/pages/fonts.dart'
    as fontspagea7872e309036a186b4b37ecf17ac9e95;
import 'shared/ui/pages/license.dart'
    as licenselist4150be05e5cdb725641fca32bbe27d41;
import 'shared/ui/pages/license_detail.dart'
    as licensedetailff9a91e0483f1ebda96cd1d2f85150d6;

/// Get route settings base on route name, auto generated by https://github.com/fluttercandies/ff_annotation_route
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
  PageBuilder? notFoundPageBuilder,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case '/announcements':
      return FFRouteSettings(
        name: '/announcements',
        arguments: arguments,
        builder: () => Announcements(key: asT<Key?>(safeArguments['key'])),
      );
    case '/bangumi/season':
      return FFRouteSettings(
        name: '/bangumi/season',
        arguments: arguments,
        builder: () => SeasonBangumi(
          key: asT<Key?>(safeArguments['key']),
          years: asT<List<YearSeason>>(safeArguments['years'])!,
        ),
      );
    case '/fonts':
      return FFRouteSettings(
        name: '/fonts',
        arguments: arguments,
        builder: () => fontspagea7872e309036a186b4b37ecf17ac9e95.FontsPage(
          key: asT<Key?>(safeArguments['key']),
        ),
      );
    case '/forget-password':
      return FFRouteSettings(
        name: '/forget-password',
        arguments: arguments,
        builder: () => ForgotPasswordPage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/index':
      return FFRouteSettings(
        name: '/index',
        arguments: arguments,
        builder: () => HomePage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/license':
      return FFRouteSettings(
        name: '/license',
        arguments: arguments,
        builder: () => licenselist4150be05e5cdb725641fca32bbe27d41.LicenseList(
          key: asT<Key?>(safeArguments['key']),
        ),
      );
    case '/license/detail':
      return FFRouteSettings(
        name: '/license/detail',
        arguments: arguments,
        builder: () =>
            licensedetailff9a91e0483f1ebda96cd1d2f85150d6.LicenseDetail(
              key: asT<Key?>(safeArguments['key']),
              packageName: asT<String>(safeArguments['packageName'])!,
              licenseEntries: asT<List<LicenseEntry>>(
                safeArguments['licenseEntries'],
              )!,
            ),
      );
    case '/login':
      return FFRouteSettings(
        name: '/login',
        arguments: arguments,
        builder: () => LoginPage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/register':
      return FFRouteSettings(
        name: '/register',
        arguments: arguments,
        builder: () => RegisterPage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/season':
      return FFRouteSettings(
        name: '/season',
        arguments: arguments,
        builder: () => SingleSeasonPage(
          key: asT<Key?>(safeArguments['key']),
          season: asT<Season>(safeArguments['season'])!,
        ),
      );
    case '/splash':
      return FFRouteSettings(
        name: '/splash',
        arguments: arguments,
        builder: () => SplashPage(key: asT<Key?>(safeArguments['key'])),
      );
    case '/subgroup':
      return FFRouteSettings(
        name: '/subgroup',
        arguments: arguments,
        builder: () => SubgroupPage(
          key: asT<Key?>(safeArguments['key']),
          subgroup: asT<Subgroup>(safeArguments['subgroup'])!,
        ),
      );
    case '/subscribed/recent':
      return FFRouteSettings(
        name: '/subscribed/recent',
        arguments: arguments,
        builder: () => RecentSubscribedPage(
          key: asT<Key?>(safeArguments['key']),
          loaded: asT<List<RecordItem>>(safeArguments['loaded'])!,
        ),
      );
    case '/subscribed/season':
      return FFRouteSettings(
        name: '/subscribed/season',
        arguments: arguments,
        builder: () => SubscribedSeasonPage(
          key: asT<Key?>(safeArguments['key']),
          years: asT<List<YearSeason>>(safeArguments['years'])!,
          galleries: asT<List<SeasonGallery>>(safeArguments['galleries'])!,
        ),
      );
    default:
      return FFRouteSettings(
        name: FFRoute.notFoundName,
        routeName: FFRoute.notFoundRouteName,
        builder: notFoundPageBuilder ?? () => Container(),
      );
  }
}
